tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
# core
brew "bash"
brew "coreutils"
brew "erlang"
brew "git"
brew "gnutls"
brew "gnupg"
brew "jq"
brew "kind"
brew "lynx"
brew "mkcert"

# dev
brew "python@3.9", link: true
brew "mongodb/brew/mongodb-community"
brew "mongodb/brew/mongodbsh"
# cask "robo-3t"
# cask "iterm2"
# cask "sublime-text"
# cask "postman"
# media
# cask "spotify"
# cask "spotmenu"
# cask "vlc"

# socials
# cask "slack"
# cask "telegram"

# misc
# cask "kindle"
# cask "calibre"
# cask "qbittorrent"
# cask "google-chrome"
# cask "openoffice"
# cask "gramps"
# cask "rectangle"
# cask "workflowy"
# cask "ticktick"
