#!/bin/bash

# enable contribs
echo ". $HOME/dotfiles/git/git-source/contrib/completion/git-completion.bash" >> ~/.bash_profile
echo ". $HOME/dotfiles/git/git-source/contrib/completion/git-prompt.sh" >> ~/.bash_profile
