# Aliases

alias ls="ls -GF"
alias ll="ls -lah"
alias speedtest="curl -s https://raw.githubusercontent.com/flamefractal/speedtest-cli/master/speedtest.py | python -"

# Git

source $HOME/dotfiles/git/aliases

# Prompt

parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

GIT_PS1_SHOWDIRTYSTATE=1

setopt PROMPT_SUBST
PROMPT='%n:%9c%{%F{green}%}$(parse_git_branch)%{%F{none}%} $ '

# NodeJS

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/work/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/work/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/work/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/work/google-cloud-sdk/completion.zsh.inc'; fi

export PATH="$PATH:$(yarn global bin)"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# Python

export PATH="/Users/work/Library/Python/3.9/bin:$PATH"

alias brew='env PATH="${PATH//$(pyenv root)\/shims:/}" brew'

# For Poetry
fpath+=~/.zfunc
