########################### CUSTOM ZSHRC STUFF

# zmodload zsh/zprof # Profile shell startup time

# General Environment Settings
export LANG="en_US.UTF-8"

# Enable autocompletion
autoload -Uz compinit && compinit

# Prompt Configuration
GIT_PS1_SHOWDIRTYSTATE=1
setopt PROMPT_SUBST
PROMPT='%n:%9c%{%F{green}%}$(parse_git_branch)%{%F{none}%} $ '

# Aliases and Functions
alias ls="ls -GF"
alias ll="ls -lah"
alias speedtest="curl -s https://raw.githubusercontent.com/flamefractal/speedtest-cli/master/speedtest.py | python3 -"
alias macscreentime="curl -s https://raw.githubusercontent.com/flamefractal/screen-on-time/main/src/screen_on_time.py | python3 -s"

# Git
source $HOME/dotfiles/git/aliases

function git() {
    case $* in
    author*)
        shift 1
        command git shortlog -s -n "$@"
        ;;
    *) command git "$@" ;;
    esac
}

parse_git_branch() {
    git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

# Python Environment
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$HOME/Library/Python/3.9/bin:$PYENV_ROOT/bin:$PATH"
command -v pyenv >/dev/null && eval "$(pyenv init -)"

# Ruby
export PATH="/opt/homebrew/opt/ruby/bin:/opt/homebrew/lib/ruby/gems/3.1.0/bin:$PATH"

# Node.js Environment
export PNPM_HOME="$HOME/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
# export PATH="$PATH:$(yarn global bin)"
# export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# Android/Flutter Environment
export PATH="$PATH:$HOME/flutter/bin:$HOME/Library/Android/sdk:$HOME/Library/Android/sdk/tools:$HOME/Library/Android/sdk/tools/bin:$HOME/Library/Android/sdk/platform-tools"

# Google Cloud SDK
if [ -f '$HOME/google-cloud-sdk/path.zsh.inc' ]; then
    . '$HOME/google-cloud-sdk/path.zsh.inc'
    . '$HOME/google-cloud-sdk/completion.zsh.inc'
fi
