########################### CUSTOM ZSHRC STUFF


# Aliases

alias ls="ls -GF"
alias ll="ls -lah"
alias speedtest="curl -s https://raw.githubusercontent.com/flamefractal/speedtest-cli/master/speedtest.py | python3 -"
alias macscreentime="curl -s https://raw.githubusercontent.com/flamefractal/screen-on-time/main/src/screen_on_time.py | python3 -s"

# Git

source $HOME/dotfiles/git/aliases

# Prompt

parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

GIT_PS1_SHOWDIRTYSTATE=1

setopt PROMPT_SUBST
PROMPT='%n:%9c%{%F{green}%}$(parse_git_branch)%{%F{none}%} $ '

# NodeJS

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH="$PATH:$(yarn global bin)"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# Python

export PATH="$HOME/Library/Python/3.9/bin:$PATH"

# alias brew='env PATH="${PATH//$(pyenv root)\/shims:/}" brew'

# Poetry
fpath+=~/.zfunc

# Ruby

export PATH="/opt/homebrew/opt/ruby/bin:/opt/homebrew/lib/ruby/gems/3.1.0/bin:$PATH"

# Android/Flutter 

export PATH="$PATH:$HOME/flutter/bin"

export ANDROID_HOME=$HOME/Library/Android/sdk 
export PATH=$PATH:$ANDROID_HOME/tools 
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH/:$ANDROID_HOME/platform-tools

# Google Cloud SDK

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/work/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/work/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/work/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/work/google-cloud-sdk/completion.zsh.inc'; fi
