export BASH_SILENCE_DEPRECATION_WARNING=1
export EDITOR='vim'

function parse_git_branch() {
	git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

function nonzero_return() {
	RETVAL=$?
	[ $RETVAL -ne 0 ] && echo "[$RETVAL]"
}

export PS1="\u:\[\e[32m\]\w:\[\e[91m\]\$(parse_git_branch)\[\e[00m\]\`nonzero_return\`$ "
