export BASH_SILENCE_DEPRECATION_WARNING=1
export EDITOR='vim'

function nonzero_return() {
	RETVAL=$?
	[ $RETVAL -ne 0 ] && echo "[$RETVAL]"
}

export GIT_PS1_SHOWDIRTYSTATE=1
export PS1="\u:\[\e[32m\]\w:\[\e[91m\]\$(__git_ps1 \" (%s)\")\[\e[00m\]\`nonzero_return\`$ "
